version: '{build}'
environment:
  APPVEYOR_IGNORE_COMMIT_FILTERING_ON_TAG: true
  MINVERBUILDMETADATA: build.%APPVEYOR_BUILD_NUMBER%
image:
- Visual Studio 2017
- Ubuntu
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - /release-.*/
init:
- cmd: dotnet --info
- sh: dotnet --info
build_script:
- ps: ./build.cmd
- sh: ./build.sh
test: off
artifacts:
- path: ./**/*.nupkg
deploy: off
